"""Minimal stubs for qgis.core – enables PyCharm autocompletion."""
from typing import Any, Optional

class QgsProject:
    @staticmethod
    def instance() -> "QgsProject": ...
    def clear(self) -> None: ...
    def setTitle(self, title: str) -> None: ...
    def setCrs(self, crs: "QgsCoordinateReferenceSystem") -> None: ...
    def addMapLayer(self, layer: "QgsMapLayer", addToLegend: bool = True) -> "QgsMapLayer": ...
    def mapLayers(self) -> dict[str, "QgsMapLayer"]: ...
    def layerTreeRoot(self) -> "QgsLayerTree": ...
    def fileName(self) -> str: ...
    def absolutePath(self) -> str: ...
    def write(self) -> bool: ...
    def setDirty(self, b: bool) -> None: ...
    def title(self) -> str: ...

class QgsCoordinateReferenceSystem:
    def __init__(self, authid: str = "") -> None: ...
    def isValid(self) -> bool: ...
    def authid(self) -> str: ...

class QgsCoordinateTransform:
    def __init__(self, src: QgsCoordinateReferenceSystem,
                 dst: QgsCoordinateReferenceSystem,
                 project: Any) -> None: ...
    def transform(self, point: "QgsPointXY") -> "QgsPointXY": ...
    def transformBoundingBox(self, rect: "QgsRectangle") -> "QgsRectangle": ...

class QgsPointXY:
    def __init__(self, x: float = 0, y: float = 0) -> None: ...
    def x(self) -> float: ...
    def y(self) -> float: ...

class QgsRectangle:
    def __init__(self, xmin: float = 0, ymin: float = 0,
                 xmax: float = 0, ymax: float = 0) -> None: ...
    def isEmpty(self) -> bool: ...
    def xMinimum(self) -> float: ...
    def yMinimum(self) -> float: ...
    def xMaximum(self) -> float: ...
    def yMaximum(self) -> float: ...
    def center(self) -> QgsPointXY: ...

class QgsVectorLayer:
    def __init__(self, uri: str, name: str, provider: str) -> None: ...
    def isValid(self) -> bool: ...
    def featureCount(self) -> int: ...
    def extent(self) -> QgsRectangle: ...
    def name(self) -> str: ...
    def id(self) -> str: ...
    def source(self) -> str: ...
    def providerType(self) -> str: ...
    def fields(self) -> "QgsFields": ...
    def loadNamedStyle(self, path: str) -> tuple[str, bool]: ...
    def setEditorWidgetSetup(self, idx: int, setup: "QgsEditorWidgetSetup") -> None: ...
    def setDefaultValueDefinition(self, idx: int, definition: "QgsDefaultValue") -> None: ...

class QgsFields:
    def indexFromName(self, name: str) -> int: ...
    def __iter__(self) -> Any: ...
    def count(self) -> int: ...

class QgsEditorWidgetSetup:
    def __init__(self, type: str, config: dict) -> None: ...

class QgsDefaultValue:
    def __init__(self, expression: str, applyOnUpdate: bool = False) -> None: ...

class QgsDataSourceUri:
    def setConnection(self, host: str, port: str, db: str,
                      user: str, password: str) -> None: ...
    def setDataSource(self, schema: str, table: str, geomColumn: str) -> None: ...
    def uri(self, expandAuthConfig: bool = True) -> str: ...

class QgsLayerTree:
    def addGroup(self, name: str) -> "QgsLayerTreeGroup": ...
    def findGroup(self, name: str) -> Optional["QgsLayerTreeGroup"]: ...

class QgsLayerTreeGroup:
    def addLayer(self, layer: QgsVectorLayer) -> None: ...
    def addGroup(self, name: str) -> "QgsLayerTreeGroup": ...
    def findGroup(self, name: str) -> Optional["QgsLayerTreeGroup"]: ...

class QgsMessageLog:
    @staticmethod
    def logMessage(msg: str, tag: str = "", level: int = 0) -> None: ...

class QgsExpressionContextUtils:
    @staticmethod
    def setProjectVariable(project: QgsProject, name: str, value: Any) -> None: ...

class QgsMapLayer:
    def name(self) -> str: ...
    def id(self) -> str: ...

class QgsRelation: ...
class QgsFeature: ...
class QgsGeometry: ...
class QgsRasterLayer: ...
class QgsCoordinateTransformContext: ...
