"""Minimal stubs for qgis.PyQt.QtCore."""
from typing import Any, Callable

class QThread:
    def start(self) -> None: ...
    def wait(self, msecs: int = -1) -> bool: ...
    def isRunning(self) -> bool: ...
    def setParent(self, parent: Any) -> None: ...
    finished: Any
    def run(self) -> None: ...

def pyqtSignal(*args: Any) -> Any: ...
