"""Minimal stubs for qgis.PyQt.QtWidgets."""
from typing import Any, Optional, Callable

class QWidget:
    def setEnabled(self, enabled: bool) -> None: ...
    def setVisible(self, visible: bool) -> None: ...
    def setParent(self, parent: Optional["QWidget"]) -> None: ...

class QDialog(QWidget):
    def exec(self) -> int: ...
    def accept(self) -> None: ...
    def reject(self) -> None: ...

class QWizard(QDialog):
    def page(self, id: int) -> Optional["QWizardPage"]: ...
    def currentPage(self) -> Optional["QWizardPage"]: ...
    def field(self, name: str) -> Any: ...
    def setProperty(self, name: str, value: Any) -> bool: ...
    def property(self, name: str) -> Any: ...
    currentIdChanged: Any
    accepted: Any
    rejected: Any
    finished: Any

class QWizardPage(QWidget):
    def wizard(self) -> Optional[QWizard]: ...
    def field(self, name: str) -> Any: ...
    def registerField(self, name: str, widget: "QWidget",
                      property: str = "", changedSignal: str = "") -> None: ...
    def setTitle(self, title: str) -> None: ...
    def setSubTitle(self, subtitle: str) -> None: ...
    def setFinalPage(self, final: bool) -> None: ...
    def initializePage(self) -> None: ...
    def validatePage(self) -> bool: ...

class QVBoxLayout:
    def addWidget(self, widget: QWidget, stretch: int = 0) -> None: ...
    def addLayout(self, layout: "QLayout") -> None: ...
    def addStretch(self, stretch: int = 1) -> None: ...

class QHBoxLayout(QVBoxLayout): ...
class QFormLayout:
    def addRow(self, label: str, widget: QWidget) -> None: ...

class QLabel(QWidget):
    def __init__(self, text: str = "", parent: Optional[QWidget] = None) -> None: ...
    def setText(self, text: str) -> None: ...
    def setWordWrap(self, wrap: bool) -> None: ...

class QLineEdit(QWidget):
    def __init__(self, text: str = "", parent: Optional[QWidget] = None) -> None: ...
    def text(self) -> str: ...
    def setText(self, text: str) -> None: ...
    def setPlaceholderText(self, text: str) -> None: ...
    def setReadOnly(self, ro: bool) -> None: ...
    class EchoMode:
        Password: int = 2
    def setEchoMode(self, mode: int) -> None: ...

class QSpinBox(QWidget):
    def value(self) -> int: ...
    def setValue(self, val: int) -> None: ...
    def setRange(self, min: int, max: int) -> None: ...
    def setFixedWidth(self, w: int) -> None: ...

class QComboBox(QWidget):
    def addItem(self, text: str, userData: Any = None) -> None: ...
    def currentText(self) -> str: ...
    def currentData(self) -> Any: ...
    def currentIndex(self) -> int: ...
    def setCurrentIndex(self, idx: int) -> None: ...
    def setEditable(self, editable: bool) -> None: ...
    def count(self) -> int: ...
    def findText(self, text: str, flags: Any = None) -> int: ...
    currentIndexChanged: Any

class QPushButton(QWidget):
    def __init__(self, text: str = "", parent: Optional[QWidget] = None) -> None: ...
    def clicked: Any
    def setEnabled(self, enabled: bool) -> None: ...
    def setDefault(self, default: bool) -> None: ...

class QCheckBox(QWidget):
    def __init__(self, text: str = "", parent: Optional[QWidget] = None) -> None: ...
    def isChecked(self) -> bool: ...
    def setChecked(self, checked: bool) -> None: ...
    toggled: Any

class QTextEdit(QWidget):
    def setReadOnly(self, ro: bool) -> None: ...
    def append(self, text: str) -> None: ...
    def clear(self) -> None: ...
    def setPlainText(self, text: str) -> None: ...
    def setFont(self, font: Any) -> None: ...
    def setMaximumHeight(self, h: int) -> None: ...

class QProgressBar(QWidget):
    def setValue(self, val: int) -> None: ...
    def setRange(self, min: int, max: int) -> None: ...
    def setVisible(self, visible: bool) -> None: ...

class QGroupBox(QWidget):
    def __init__(self, title: str = "", parent: Optional[QWidget] = None) -> None: ...
    def setLayout(self, layout: Any) -> None: ...
    def setEnabled(self, enabled: bool) -> None: ...

class QFileDialog:
    @staticmethod
    def getExistingDirectory(parent: Any = None, caption: str = "") -> str: ...
    @staticmethod
    def getOpenFileName(parent: Any = None, caption: str = "",
                       filter: str = "") -> tuple[str, str]: ...

class QTabWidget(QWidget):
    def addTab(self, widget: QWidget, label: str) -> int: ...

class QTreeWidget(QWidget):
    def setHeaderLabels(self, labels: list[str]) -> None: ...
    def setColumnWidth(self, col: int, width: int) -> None: ...
    def setItemWidget(self, item: Any, col: int, widget: QWidget) -> None: ...

class QTreeWidgetItem:
    def __init__(self, parent: Any = None) -> None: ...
    def setText(self, col: int, text: str) -> None: ...
    def setExpanded(self, expand: bool) -> None: ...
